version: '3.7'

services:
  mysql:
    container_name: shopp_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: longmetmoivcl
      MYSQL_DATABASE: shopp
    ports:
      - 3307:3307
    networks:
      - shopp
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  be:
    container_name: shopp_be
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - 'npm run generate:migration && npm run run-migration && npm start'
    ports:
      - 3001:3001
    depends_on:
      - mysql
    networks:
      - shopp
    restart: always

volumes:
  mysql-data:

networks:
  shopp:
    driver: bridge